"""
Emit an importable, dependency-free Python module snapshot of the registry
for projects that would rather vendor a file than depend on modelroster.

    modelroster emit --out models_snapshot.py [--provider X ...] [--filter tool_calling=true ...]

The module exposes `MODELS` ({"provider/model_id": {...}}), per-provider
`<PROVIDER>_MODELS` dicts keyed by model id, `<PROVIDER>_MODEL_IDS` tuples in
the provider's own order, and `REFRESHED`. Values are tri-state: None means
"not documented", never "no". The file is compiled before it is written.
"""

from __future__ import annotations

import time
from typing import Any, Iterable

from ._version import __version__
from .registry import Registry
from .schema import PARSER_VERSION, ModelRecord
from .store import write_text_atomic

GENERATED_HEADER = '''# =============================================================================
# GENERATED FILE — DO NOT EDIT BY HAND.
#
# Generated by modelroster %(version)s (parser %(parser)s) at %(when)s
# Regenerate with:   modelroster emit --out <this file> %(args)s
#
# Values are documentation/API-derived and tri-state: None means
# "the source does not say", not "no".
# =============================================================================
'''

SNAPSHOT_FIELDS = (
    "display_name", "family", "relationship", "aliases", "snapshots", "default_snapshot", "released",
    "deprecated", "shutdown_date", "context_window", "max_input_tokens", "max_output_tokens",
    "knowledge_cutoff", "reasoning", "reasoning_efforts", "default_effort", "extended_thinking",
    "tool_calling", "structured_outputs", "streaming", "prompt_caching", "fine_tuning", "batch",
    "citations", "code_execution", "pdf_input", "image_input", "audio_input", "video_input",
    "image_output", "audio_output", "endpoints", "builtin_tools", "pricing",
)


def _lit(v: Any, indent: int = 0) -> str:
    pad = "    " * indent
    if v is None or isinstance(v, bool):
        return repr(v)
    if isinstance(v, int):
        return ("%d" % v) if abs(v) < 10_000 else ("{:_}".format(v))
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, str):
        return repr(v)
    if isinstance(v, (list, tuple)):
        if not v:
            return "()"
        return "(" + ", ".join(_lit(x) for x in v) + ("," if len(v) == 1 else "") + ")"
    if isinstance(v, dict):
        if not v:
            return "{}"
        lines = ["{"]
        for k, val in v.items():
            lines.append(pad + "    " + repr(k) + ": " + _lit(val, indent + 1) + ",")
        lines.append(pad + "}")
        return "\n".join(lines)
    raise TypeError("cannot render %r" % type(v))


def snapshot_entry(rec: ModelRecord) -> dict[str, Any]:
    c = rec.capabilities
    return {
        "display_name": rec.display_name, "family": rec.family, "relationship": rec.relationship,
        "aliases": tuple(rec.aliases), "snapshots": tuple(rec.snapshots), "default_snapshot": rec.default_snapshot,
        "released": rec.released, "deprecated": rec.deprecated, "shutdown_date": rec.shutdown_date,
        "context_window": rec.context_window, "max_input_tokens": rec.max_input_tokens,
        "max_output_tokens": rec.max_output_tokens, "knowledge_cutoff": rec.knowledge_cutoff,
        "reasoning": c.reasoning, "reasoning_efforts": tuple(c.reasoning_efforts) if c.reasoning_efforts is not None else None,
        "default_effort": c.default_effort, "extended_thinking": c.extended_thinking,
        "tool_calling": c.tool_calling, "structured_outputs": c.structured_outputs, "streaming": c.streaming,
        "prompt_caching": c.prompt_caching, "fine_tuning": c.fine_tuning, "batch": c.batch,
        "citations": c.citations, "code_execution": c.code_execution, "pdf_input": c.pdf_input,
        "image_input": rec.modality("image"), "audio_input": rec.modality("audio"), "video_input": rec.modality("video"),
        "image_output": rec.modality("image", "output"), "audio_output": rec.modality("audio", "output"),
        "endpoints": dict(rec.endpoints), "builtin_tools": dict(rec.builtin_tools) if rec.builtin_tools is not None else None,
        "pricing": {k: rec.pricing.get(k) for k in ("input", "output", "cached_input")} if rec.pricing else None,
    }


def render_module(registry: Registry, providers: Iterable[str] | None = None, args_hint: str = "",
                  **filters: Any) -> str:
    provs = list(providers) if providers else registry.providers()
    when = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    parts = [GENERATED_HEADER % {"version": __version__, "parser": PARSER_VERSION, "when": when, "args": args_hint}]
    refreshed = {p: (registry.envelope(p).get("retrieved_at") or "")[:10] for p in provs}
    parts.append("\nREFRESHED = " + _lit(refreshed) + "\n")
    all_models: dict[str, Any] = {}
    for p in provs:
        entries = {r.model_id: snapshot_entry(r) for r in registry.models(p, **filters)}
        const = p.upper().replace("-", "_")
        parts.append("\n%s_MODELS = %s\n" % (const, _lit(entries)))
        parts.append("\n%s_MODEL_IDS = tuple(%s_MODELS.keys())\n" % (const, const))
        for mid, e in entries.items():
            all_models["%s/%s" % (p, mid)] = dict(e, provider=p, model_id=mid)
    parts.append("\nMODELS = {\n" + "".join(
        "    %r: dict(%s_MODELS[%r], provider=%r, model_id=%r),\n" % (k, k.split("/", 1)[0].upper().replace("-", "_"), k.split("/", 1)[1], k.split("/", 1)[0], k.split("/", 1)[1])
        for k in all_models) + "}\n")
    parts.append("\nMODEL_IDS = tuple(MODELS.keys())\n")
    return "".join(parts)


def compile_check(text: str) -> dict[str, Any]:
    ns: dict[str, Any] = {}
    exec(compile(text, "<modelroster-snapshot>", "exec"), ns)
    return ns


def emit(registry: Registry, out_path, providers: Iterable[str] | None = None, **filters: Any) -> dict[str, Any]:
    text = render_module(registry, providers, **filters)
    ns = compile_check(text)
    write_text_atomic(out_path, text)
    return ns
